### ISSUE TITLE
Support for author data and such

### ISSUE THREAD

**Issue by TheOnlyWayUp** [bentettmar/discord.py-self_embed#3]
Raul's gen doesn't support it, but can you create your own embed generator using Jinja2's embeds and something like FastAPI to accept query strings & parse and return/render.

You can use `json+oembed` tags to add support for 
- Author names and URLs
- Provider names and URLs
- Titles

You can use `og:` to add support for
- Titles
- Descriptions
- Images

You can use `meta:theme-color` to add support for custom embed colors.

[Tutorial](https://www.reddit.com/r/discordapp/comments/82p8i6/a_basic_tutorial_on_how_to_get_the_most_out_of/)

**Comment by bennyscripts** [comment]
I know about oembed but for sake of convenience I'm using raufs gen.

**Comment by bennyscripts** [comment]
I will consider this though. Would love to use the benefits of oembed.
